function img_cropper(imgexp,folder)

% crops images generated by scope to center quadrant

files = file_search(imgexp,folder);
for i = 1:length(files)
    a = double(imread(files{i}));
    acrop = a(513:1536,513:1536);
    imwrite2tif(acrop,[],fullfile(folder,['crop_' files{i}]),'single')
end

end